### ISSUE TITLE
How to send data back to container in electron-react-boilerplate?

### ISSUE THREAD

**Issue by vjtc0n** [Slapbox/electron-notification-demo#1]
Could you show me how to do this ?

I'm a beginner in electron-react.

I posted an issues here: https://github.com/blainesch/electron-notifications/issues/25

Thank you!

**Comment by Slapbox** [comment]
Hey @vjtc0n 

Just a heads up that the purpose of this repo is actually to demonstrate an issue that causes the notifications to not work once the application is packaged, so before you get too attached, keep in mind that currently there is no fix for this, although I have asked a few smart people to take a look and hope someone can point me towards the answer.

I will respond to your issue on blainesch's repo so others using the package are more likely to see.
